/**
 * Stable public entry point for the `schemd` server-side compiler.
 *
 * All runtime exports are dependency-free and safe to run without a DOM.
 *
 * @packageDocumentation
 */
export { parseSchematic, parseSchematicColor, parseSchematicFence } from './parser.js';
export { renderSchematic } from './renderer.js';
export {
	compileSchematic,
	schematicSourceMap,
	type SchematicCompilation,
	type SchematicCompilationMetrics,
	type SchematicSourceMap,
	type SchematicNodeSource,
	type SchematicWireSource
} from './compiler.js';
export {
	mathLabelGlyphLength,
	mathLabelTextWidth,
	mathLabelText,
	parseMathLabel,
	renderMathLabelTspans,
	type MathLabelSegment,
	type MathLabelSegmentKind
} from './math-label.js';
export {
	MAX_SCHEMATIC_COMPONENTS,
	MAX_SCHEMATIC_CONNECTIONS,
	MAX_SCHEMATIC_WIRE_CROSSINGS,
	MAX_SCHEMATIC_SOURCE_CHARACTERS,
	MAX_SCHEMATIC_SVG_OUTPUT_BYTES,
	SCHEMATIC_LIMITS
} from './limits.js';
export {
	classicalGateHeight,
	composeQuarterTurns,
	componentObstacleRectangle,
	componentRectangle,
	componentTextAnchors,
	connectionLabelPoint,
	connectionLabelRectangle,
	distributedCoordinate,
	enumerateComponentPorts,
	positionIcPin,
	PORT_HOTSPOT_RADIUS,
	quantumGateDimensions,
	orientationQuarterTurn,
	inverseQuarterTurn,
	resolvePortPoint,
	resolvePortGeometry,
	rotateQuarterExtents,
	rotateQuarterPoint,
	routeConnections,
	routeConnection,
	SCHEMATIC_BRIDGE_RADIUS,
	SCHEMATIC_OBSTACLE_CLEARANCE,
	validateDocumentGeometry,
	type RoutedConnection,
	type ComponentTextAnchors,
	type ComponentPort,
	type IcPinSide,
	type SchematicHalfExtents,
	type SchematicRectangle
} from './layout.js';
export {
	ANALOG_KINDS,
	ADDER_TYPES,
	AMPLIFIER_TYPES,
	BUFFER_TYPES,
	BUS_TYPES,
	COMPONENT_KINDS,
	CLASSICAL_GATE_KINDS,
	DIGITAL_COMPONENT_KINDS,
	DIODE_TYPES,
	ELECTRICAL_COMPONENT_KINDS,
	FLIPFLOP_TYPES,
	GROUND_STYLES,
	LOAD_TYPES,
	LOGIC_STATES,
	METER_TYPES,
	MUX_TYPES,
	NAMED_QUANTUM_GATE_KINDS,
	PASSIVE_KINDS,
	PASSIVE_TYPES,
	POWER_TYPES,
	PROTECTION_TYPES,
	QUANTUM_GATE_KINDS,
	QUANTUM_SPECIAL_KINDS,
	RESONATOR_TYPES,
	SCHEMATIC_ORIENTATIONS,
	SCHEMATIC_SIGNAL_KINDS,
	SCHEMATIC_SIGNAL_MARKERS,
	SEMANTIC_COLORS,
	SOURCE_TYPES,
	SWITCH_TYPES,
	TRANSISTOR_TYPES,
	UML_COMPONENT_KINDS,
	UML_RELATION_KINDS,
	SCHEMD_OUTPUT_MODES,
	SCHEMD_SEMANTIC_HOOKS,
	SchematicSyntaxError,
	type AnalogKind,
	type AdderType,
	type AmplifierType,
	type BufferType,
	type BusType,
	type CompileSchematicOptions,
	type ClassicalGateComponent,
	type ClassicalGateKind,
	type DigitalComponent,
	type DigitalComponentKind,
	type ElectricalComponent,
	type ElectricalComponentKind,
	type ElectricalVariant,
	type ComponentKind,
	type DiodeComponent,
	type DirectionalComponentBase,
	type DiodeType,
	type GroundComponent,
	type GroundStyle,
	type FlipFlopType,
	type IcComponent,
	type IntegratedCircuitComponent,
	type IntegratedCircuitPins,
	type PassiveComponent,
	type PassiveKind,
	type PassiveType,
	type LoadType,
	type LogicState,
	type MeterType,
	type MuxType,
	type PowerType,
	type ProtectionType,
	type PortComponent,
	type SemanticColor,
	type SchematicBounds,
	type SchematicComponent,
	type SchematicConnection,
	type SchematicColor,
	type SchematicDocument,
	type SchematicEndpoint,
	type SchematicFence,
	type SchematicOrientation,
	type SchematicSignalMarker,
	type SchematicSemanticHook,
	type SchematicPoint,
	type SchematicQuarterTurn,
	type SchemdOutputMode,
	type TransistorComponent,
	type TransistorType,
	type QuantumGateComponent,
	type QuantumGateKind,
	type QuantumSpecialComponent,
	type QuantumSpecialKind,
	type NamedQuantumGateKind,
	type ResonatorType,
	type SchematicSignalKind,
	type SourceType,
	type SwitchType,
	type SchematicRelationKind,
	type UmlActorComponent,
	type UmlClassComponent,
	type UmlComponent,
	type UmlComponentKind,
	type UmlPseudostateComponent,
	type UmlRelationKind,
	type UmlSizedComponent,
	type UmlStateComponent
} from './types.js';
